#!/bin/bash
#running the gender count example on spark

source /home/anshuman/devstack/openrc
echo "" > /var/www/jproject.ca/docs/spark/output.txt
echo "" > /var/www/jproject.ca/docs/spark/output2.txt
#echo "starting the gender language count"

ssh -i ~/.ssh/cloud.key ubuntu@172.24.42.5 "sudo bash /home/ubuntu/spark-1.5.1/bin/spark-submit --master spark://10.0.0.30:7077 /home/ubuntu/spark-1.5.1/examples/src/main/python/genderlanguagecount.py &"

#echo "count complete"
